### ISSUE TITLE
Missing typings on Card component (and maybe others)

### ISSUE THREAD

**Issue by Profex1999** [wix/react-native-ui-lib#2202]
### Related to

- [ ] Components
- [ ] Demo
- [ ] Docs
- [x] Typings

#### Expected behavior
This is with version 6.18.0
<img width="503" alt="Screenshot 2022-08-18 at 15 50 17" src="https://user-images.githubusercontent.com/51895814/185411497-66991e88-51ff-4ca5-aed6-6644ed99182c.png">

#### Actual behavior
This is with version >= 6.19
<img width="517" alt="Screenshot 2022-08-18 at 15 51 02" src="https://user-images.githubusercontent.com/51895814/185411705-82cd0ac8-f1ad-480c-8ef4-0115df1027ce.png">

### Code snippet
N/A

### Screenshots/Video
See above

### Environment

- React Native version: 0.69
- React Native UI Lib version: 6.20.1
- Typescript 4.4.4
- React 18.0.0

### Affected platforms
None, only VSCode
- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by robinclaes** [comment]
Same issue here! Downgrading to 6.18 resolves it, so its definitely a regression.

![image](https://user-images.githubusercontent.com/11699918/187526167-037db295-49ee-4b8b-993f-1a0147795189.png)

**Comment by CodingMeSwiftly** [comment]
Same issue here! Can confirm downgrade to `6.18` as a workaround.
Problem is, the component type gets changed on import from `React.ComponentClass<#PropsClass#, any>` to `React.ComponentClass<any, any>`.  Makes the latest version of this library completely unusable in typescript, unfortunately.

**Comment by lakardion** [comment]
Any updates on this? 
I am also experiencing the same issue with various components (Text, Picker) in latest version
![image](https://user-images.githubusercontent.com/52294448/199000087-eae95ca1-b72b-4686-8532-38c7a23c25be.png)
![image](https://user-images.githubusercontent.com/52294448/199000131-bdd9c21d-95ae-41cf-badf-2c99be54529f.png)

**Comment by The-White-Fang** [comment]
I think I've found the issue. Inside `react-native-ui-lib/typings/globalTypes.d.ts` there is a declaration`declare module 'react-native-measureme';`. And inside this file the `ThemeComponent` interface is defined. I think the ts-server is unable to resolve `ThemeComponent` which has been used throughout the library. And surely enough, these components have the broken typings. I was hoping to submit a PR but it seems the master branch is a little messed up and I was getting `peer-dependency` errors, upon using the `-f` flag the project failed the tests as it complained about some files missing. 

@ethanshar can you help me with these issues so I can submit a PR?

**Comment by The-White-Fang** [comment]
Seems like the problem is created by a global type `ThemeComponent` declared in `globalTypes` file. For some reason the global types are not resolving correctly and since the `asBaseComponent` function uses it like `PROPS & ThemeComponent`, the passed props are ignored as well. I tried to fix it with a PR but it seems that something is wrong with either my setup or the code (Latter one most likely) as I was unable to build (`npm run build`) the package and kept running into an error 
```
Error: Command failed: tsc --p tsconfig.build.json
    at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
    at Object.<anonymous> (/home/abhishek/react-native-ui-lib/scripts/build.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  status: 2,
  signal: null,
  output: [
    null,
    Buffer(292) [Uint8Array] [
      115, 114,  99,  47,  99, 111, 109, 112, 111, 110, 101, 110,
      116, 115,  47, 115, 108, 105, 100, 101, 114,  47,  95,  95,
      116, 101, 115, 116, 115,  95,  95,  47, 105, 110, 100, 101,
      120,  46, 115, 112, 101,  99,  46, 116, 115, 120,  40,  52,
       44,  50,  56,  41,  58,  32, 101, 114, 114, 111, 114,  32,
       84,  83,  50,  51,  48,  55,  58,  32,  67,  97, 110, 110,
      111, 116,  32, 102, 105, 110, 100,  32, 109, 111, 100, 117,
      108, 101,  32,  39,  46,  46,  47,  83, 108, 105, 100, 101,
      114,  46, 100, 114,
      ... 192 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 13449,
  stdout: Buffer(292) [Uint8Array] [
    115, 114,  99,  47,  99, 111, 109, 112, 111, 110, 101, 110,
    116, 115,  47, 115, 108, 105, 100, 101, 114,  47,  95,  95,
    116, 101, 115, 116, 115,  95,  95,  47, 105, 110, 100, 101,
    120,  46, 115, 112, 101,  99,  46, 116, 115, 120,  40,  52,
     44,  50,  56,  41,  58,  32, 101, 114, 114, 111, 114,  32,
     84,  83,  50,  51,  48,  55,  58,  32,  67,  97, 110, 110,
    111, 116,  32, 102, 105, 110, 100,  32, 109, 111, 100, 117,
    108, 101,  32,  39,  46,  46,  47,  83, 108, 105, 100, 101,
    114,  46, 100, 114,
    ... 192 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}
```

and I really don't have a clue about what's wrong here. Though `npm run build:dev` seems to be working just fine.

**Comment by The-White-Fang** [comment]
As a workaround to get the typings back for now I am going to the definition files for the components I am using, and adding an import to `ThemeComponent`.
```
import { ThemeComponent } from 'react-native-ui-lib/typings';
``` 

Also, note that you will need to modify the `typings/globalTypes.d.ts` and add an `export` before the `ThemeComponent`'s definition like so
```
export interface ThemeComponent {
  useCustomTheme?: boolean;
}
```

This is not the ideal solution as you would have to do it each time you reinstall the library, but if you care about the typing you will have to bare with it until it is officially fixed.

**Comment by SchneiderOr** [comment]
Hey all!
Based on the answers here i created a [**patch-package** gist](https://gist.github.com/SchneiderOr/9cafb510bb817813e0e0eee291572382) to fix the issue with latest version until a proper fix will be provided
I've exported the ThemedComponent type from globals and added explicit import to it in every type that uses it.
you can use [patch-package](https://github.com/ds300/patch-package) to apply it in your code

It's a bit troubling that this issue is open more than half a year while the package do get updated but no one address this

**Comment by denbka** [comment]
same issue ...............

**Comment by HarunKilic** [comment]
Same issue on Button

**Comment by ronal2s** [comment]
Same issues here, waiting for the next release, using version 18 for now

**Comment by chrismerino** [comment]
Same issue

**Comment by aboozaid** [comment]
and here is a fix for fontWeight issue and types for version 7.2.4 [patch-package patch](https://gist.github.com/aboozaid/13f5b217651f68ba4f03e8df11014e0e)

**Comment by The-White-Fang** [comment]
any update on when it will be fixed or if it is on the roadman? @ethanshar

**Comment by ethanshar** [comment]
Should be resolved in our next version

**Comment by Revolt9k** [comment]
Still experience it on `7.6.0`. What exactly _next version?_

**Comment by ethanshar** [comment]
Should be fixed in 7.7.0
Try installing `snapshot` tag version and see if it's working 
The new version should be out next week
