### ISSUE TITLE
Picker Search not working

### ISSUE THREAD

**Issue by LorenDorez** [wix/react-native-ui-lib#3166]
## Description

I copied the example picker from the Demo app but unfortunately searching doesnt appear to work. Im using Expo Go incase that might be an issue.

### Related to
- Picker

### Steps to reproduce

1. Load the component
2. Click to open the picker and see the list of langs
3. Type in `ada` to the search

#### Expected behavior

When I type `ada` the list should filter down

#### Actual behavior

Does nothing

### Code snippet

```typescript
import { longOptions } from "@/utils/dev/PickerScreenLongOptions";
import { useState } from "react";
import { Colors, Picker } from "react-native-ui-lib";

export default function CompanyPicker() {
    const [language, setLanguage] = useState();
    return (
        <Picker
            placeholder="Favorite Language"
            floatingPlaceholder
            value={language}
            enableModalBlur={false}
            onChange={item => setLanguage(item)}
            topBarProps={{title: 'Languages'}}
            // style={{color: Colors.red20}}
            showSearch
            searchPlaceholder={'Search a language'}
            searchStyle={{color: Colors.blue30, placeholderTextColor: Colors.grey50}}
            // onSearchChange={value => console.warn('value', value)}
            items={longOptions}
          />
    );
}
````

### Environment
- React Native version: 0.74.3
- React Native UI Lib version: ^7.25.0
- Expo: 51

### Affected platforms

- [X] Android
- [X] iOS

**Comment by LorenDorez** [comment]
Doing some more digger the `usePickerSearch` gets passed in children but in my case this appears to be undefined, should this pass in the items prop and not children?

**Comment by LorenDorez** [comment]
So looks like it works if i move my items to the children like such:

```typescript
import { longOptions } from "@/utils/dev/PickerScreenLongOptions";
import { useState } from "react";
import { Colors, Picker } from "react-native-ui-lib";

export default function CompanyPicker() {
    const [language, setLanguage] = useState();
    return (
        <Picker migrate
            placeholder="Favorite Language"
            floatingPlaceholder
            value={language}
            enableModalBlur={false}
            onChange={item => setLanguage(item)}
            topBarProps={{title: 'Languages'}}
            // style={{color: Colors.red20}}
            showSearch
            searchPlaceholder={'Search a language'}
            searchStyle={{color: Colors.blue30, placeholderTextColor: Colors.grey50}}
            // onSearchChange={value => console.warn('value', value)}
            //items={longOptions}
        >
            {longOptions.map(option => (
              <Picker.Item key={option.value} value={option.value} label={option.label} disabled={option.disabled}/>
            ))}
        </Picker>
    );
}
```

**Comment by Akash9923** [comment]
Above code is working

**Comment by adids1221** [comment]
Hi, we are working on fix for this.
[related PR](https://github.com/wix/react-native-ui-lib/pull/3070)

**Comment by adids1221** [comment]
The fix was merged, should be released in the next version.

**Comment by dlowryjs** [comment]
@adids1221 has this been released? we are still facing this issue

**Comment by adids1221** [comment]
Hi @dlowryjs yes it's been released.
Add code snippet here please so I can take a look.

**Comment by dlowryjs** [comment]
```
  return (
    <Picker
      ref={pickerRef}
      onPress={onPress}
      value={selectedValue}
      onChange={(value) => {
      }
      placeholderTextColor={Colors.PlaceholderInput}
      items={options}
      renderItem={(value, { isSelected }, label) => (
        <PickerItem label={label ?? ''} isSelected={isSelected} />
      )}
    />
```
The issue occurs when I am using the `items` prop and passing a custom PickerItem through `renderItem`. Everything renders and is selectable, however search is unresponsive. I have been able to work around this by mapping my options to our custom PickerItems as children, however that required more special handling like passing an onChange prop to our PickerItem, as well as passing in `closeExpandable` so I can close the Picker on selection.

**Comment by dlowryjs** [comment]
@adids1221 disregard this- i just realized I am not on the latest version. Let me upgrade and confirm.

**Comment by adids1221** [comment]
@dlowryjs ok, waiting for your update.

**Comment by dlowryjs** [comment]
Hi @adids1221 apologies for the delay- it is working on our end. Thank you!
